/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GAME2048 } from "./GAME2048";
export * as factories from "./factories";
export { GAME2048__factory } from "./factories/GAME2048__factory";
